name: babapro

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Cria Imagem Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checking out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Push to Github Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          version: ${{ steps.extract_branch.outputs.branch }}
          file: Dockerfile
          target: production
          push: true
          tags: "ghcr.io/${{ github.repository }}:${{ steps.extract_branch.outputs.branch }}"
